#!/bin/sh
case "$BLOCK_BUTTON" in
	1|2|3)
		pactl set-sink-mute 0 toggle && pkill -RTMIN+10 i3blocks
		;;
    4)
		pactl set-sink-volume 0 +5% && pactl set-sink-mute 0 0 && pkill -RTMIN+10 i3blocks
		;;
	5)
		pactl set-sink-volume 0 -5% && pkill -RTMIN+10 i3blocks
		;;
esac

amixer get Master | awk '{if($6=="[on]"){print $5}else{print "MUTE"}}' | tr -d '[]' | tail -n 1 | tr -d "%" | awk '{if ($1 == "MUTE" || $1 == 0) {print "&#xf026;", $1 "%"} else if($1 < 45) {print "&#xf027;", $1 "%"} else {print "&#xf028;", $1 "%"}}'
