#!/bin/sh
amixer get Master | awk '{if($6=="[on]"){print $5}else{print "MUTE"}}' | tr -d '[]' | tail -n 1 | tr -d "%" | awk '{if ($1 == "MUTE" || $1 == 0) {print "&#xf026;", $1 "%"} else if($1 < 45) {print "&#xf027;", $1 "%"} else {print "&#xf028;", $1 "%"}}'
