#!/bin/sh
#top -bn1 | grep "%Cpu" | awk '{ print $3 }' | tr -d "\n" | awk '{ print $1 + $2 + $3 + $4 }'
iostat -c | sed '4q;d' | awk '{print 100-$6}'
#mpstat 1 1 | tail -n 1 | awk '{print 100 - $12 ""}'
