#!/bin/bash
VLC_PID=/tmp/music-player-pid

if [ -f "$VLC_PID" ]
then
	#echo "&#xf0a9; "
	#echo "&#xf050; "
	echo "&#xf04e; "
	case "$BLOCK_BUTTON" in
    1|2|3)
		playerctl --player=vlc next
	esac
fi
