#!/bin/sh
USAGE=$($CONFIGS/i3blocks/i3b-cpu)
echo "&#xf1ec; $USAGE%"
case "$BLOCK_BUTTON" in 1|2|3)
	echo -e "CPU usage: $USAGE \n$(top -bn1 | grep "%Cpu")\n-----------------\nTop cpu proccesses:\n$(shmem)"  \
	| rofi \
		-dmenu \
		-markup-rows \
		-no-fullscreen \
		-hide-scrollbar \
		-bw 1 \
		-eh 1 \
		-m -3 \
		-no-custom \
		-width 50 \
		-theme-str "#window {anchor: northeast;}" \
		-p "System info" > /dev/null

esac
