#!/bin/bash

active_connections=$( nmcli device status |  awk '{if($3 == "connected"){type=$2;$1=$2=$3=""; print type":"$0}}')

if [[ $active_connections =~ "wifi" ]]; then
    wifi_connection=$(nmcli device wifi | awk '{if($1=="*"){print $3" "$9}}')
    wifi_name=$(echo $wifi_connection | cut -f1 -d " ")
    active_connections="${active_connections//$wifi_name/$wifi_connection}"
fi

active_connections="${active_connections//ethernet/&#xf6ff;}"
active_connections="${active_connections//wifi/&#xf1eb;}"
echo $active_connections