#!/bin/bash
VLC_PID=/tmp/vlc-i3-player/music-player-pid

if [ -f "$VLC_PID" ]
then
	#echo " &#xf0a8;"
	#echo " &#xf049;"
	echo " &#xf04a;"
	case "$BLOCK_BUTTON" in
    1|2|3)
		playerctl --player=vlc previous
	esac
fi
