#!/bin/bash

ERROR_LOG="$HOME/ssw-7.log"

while [ "$menu" != 6 ]
do
	echo '============================='
	echo 'Amazing and simple ssw script'
	echo '1. Make directory'
	echo '2. Change current directory'
	echo '3. Print work directory content'
	echo '4. Move file'
	echo '5. Remove directory with files'
	echo '6. Exit'

	read menu

	case "$menu" in
		1)
			echo 'Directory name:'
			read dir_name
			mkdir "$dir_name" 2>>"$ERROR_LOG" || echo "Error. See $ERROR_LOG for more info." 1>&2
		;;

		2)
			echo 'Destination:'
			read dir_name
			cd "$dir_name" 2>>"$ERROR_LOG" || echo "Error. See $ERROR_LOG for more info." 1>&2
		;;

		3)
			ls-l 2>>"$ERROR_LOG" || echo "Error. See $ERROR_LOG for more info." 1>&2
		;;

	       	4)
			echo 'Enter source file:'
			read src
			echo 'Enter destination:'
			read dst
			mv "$src" "$dst"  2>>"$ERROR_LOG" || echo "Error. See $ERROR_LOG for more info." 1>&2
		;;

		5)
			echo 'Directory name:'
			read dir_name
			rm -r "$dir_name" 2>>"$ERROR_PATH"  || echo "Error. See $ERROR_LOG for more info." 1>&2
		;;

		6) ;;

		*)
			echo 'Wrong option'
			;;
	esac
done
