#!/bin/bash
VLC_PID_FILE=/tmp/music-player-pid
OPT=$(ls -1 $HOME/Music)
CHOSEN=$($CONFIGS/i3/rofi-menu -f 15 -w 45 -l 20 -h "Choose an album" -t "$OPT")



if [ -z "$CHOSEN" ]
then
	#notify-send "Playlist not specified"
	:
else
	if [ -f "$VLC_PID_FILE"  ]
	then
		VLC_PID=$(cat $VLC_PID_FILE)
		kill -9 "$VLC_PID"
		rm $VLC_PID_FILE
	fi
	PLAYLIST="$HOME/Music/$CHOSEN"
	notify-send "Playing now: $CHOSEN"
	cvlc  "$PLAYLIST" &
	echo "$!" > $VLC_PID_FILE
	pkill -RTMIN+15 i3blocks
fi

