#!/bin/bash
VLC_PID_DIR=/tmp/vlc-i3-player
VLC_PID_FILE=$VLC_PID_DIR/music-player-pid


OPT=$(ls -1 $HOME/Music)
CHOSEN=$($CONFIGS/i3/rofi-menu -f 15 -w 45 -l 23 -h "Choose an album" -t "$OPT")



if [ -z "$CHOSEN" ]
then
	#notify-send "Playlist not specified"
	:
else
	mkdir -p $VLC_PID_DIR
	if [ -f "$VLC_PID_FILE"  ]
	then
		VLC_PID=$(cat $VLC_PID_FILE)
		kill -9 "$VLC_PID"
		rm $VLC_PID_FILE
	fi
	PLAYLIST="$HOME/Music/$CHOSEN"
	echo $PLAYLIST > $VLC_PID_DIR/playlist
	notify-send "Playing now: $CHOSEN"
	cvlc -L "$PLAYLIST" &
	echo "$!" > $VLC_PID_FILE
	pkill -RTMIN+15 i3blocks
fi

