#!/bin/sh
DIR="~/Images/Screenshots"
name="$(echo 'screen-')$(date +%H:%M:%S)$(echo '.png')"
if [ "$1" == "-s" ]; then
	scrot $name -s -q 100 -e "mkdir $DIR/%d-%m-%Y ; mv \$f $DIR/%d-%m-%Y/"
else
	scrot $name -q 100 -e "mkdir $DIR/%d-%m-%Y ; mv \$f $DIR/%d-%m-%Y/"
fi
