#!/bin/sh
while true
do
	temp=$(top -bn1 | grep "%Cpu" | awk '{print $3}' | tr "\n" " " | awk '{print ($1 + $2 + $3 + $4), "400"}' | graph_stat)
	I3BLOCKS_CPU="$(env_cutter $I3BLOCKS_CPU)$temp"
	echo $I3BLOCKS_CPU
	sleep 2
done
