#!/bin/sh
#set your own png here
I3LOCK_BG=~/Images/wp/manjaro-7.png
CHOSEN=$(echo -e " &#xf137; Logout\n &#xf011; Poweroff\n &#xf0e2; Reboot\n &#xf023; Lock\n &#xf017; Suspend" \
		| rofi \
			-dmenu \
			-font "Noto Mono 14" \
			-markup-rows \
			-no-fullscreen \
			-hide-scrollbar \
			-m -1 \
			-width -22 \
			-no-custom \
			-color-window "#222222, #222222, #b1b4b3" \
			-color-normal "#222222, #CCCCCC, #222222, #005577, #FFFFFF" \
			-lines 5 \
			-separator-style solid \
			-p "Exit menu"
		)
case "$CHOSEN" in
	" &#xf137; Logout" )
		i3-msg exit
	;;

	" &#xf011; Poweroff" )
		/usr/bin/systemctl poweroff
	;;

	" &#xf0e2; Reboot" )
		/usr/bin/systemctl reboot
	;;

	" &#xf023; Lock" )
		i3lock -fei $I3LOCK_BG
	;;

	" &#xf017; Suspend" )
		i3lock -fei $I3LOCK_BG && /usr/bin/systemctl suspend
	;;

esac
