#!/bin/sh
awk 'BEGIN {s0="⠀"; s1="▁"; s2="▂"; s3="▃"; s4=""; s5="▅"; s6="▆"; s7="▇";} {temp=$1/$2; if(temp>=0 && temp<0.125) print s0; else if(temp>=0.125 && temp<0.25) print s1; else if(temp>=0.25 && temp<0.375) print s2; else if (temp>=0.375 && temp<0.5) print s3; else if(temp>=0.5 && temp<0.625) print s4; else if(temp>=0.625 && temp<0.75) print s5; else if (temp>=0.75 && temp<0.875) print s6; else if(temp>=0.875 && <=1) print s7;}'

