#!/bin/bash
I3B_GRAPH_MEM="_____"
while true
do
 	USAGE=$(free -m | tr "\n" " " | awk '{print $9, $8}' | i3b-graph-builder)
	I3B_GRAPH_MEM="$(echo ${I3B_GRAPH_MEM:1:5})$USAGE"
	echo $I3B_GRAPH_MEM
	sleep 2
done
