#!/bin/sh
while true
do
	USAGE=$(top -bn1 | grep "%Cpu" | awk '{print $3}' | tr "\n" " " | awk '{print ($1 + $2 + $3 + $4), "400"}' | i3b-graph-builder)
	I3BLOCKS_CPU="$(i3b-graph-env-cutter $I3BLOCKS_CPU)$USAGE"
	echo $I3BLOCKS_CPU
	sleep 2
done
