#!/bin/sh
name="$(echo 'screen-')$(date +%H:%M:%S)$(echo '.png')"
if [ "$1" == "-s" ]; then
	scrot $name -s -q 100 -e 'mkdir ~/Images/Screenshots/%d-%m-%Y ; mv $f ~/Images/Screenshots/%d-%m-%Y/'
else
	scrot $name -q 100 -e 'mkdir ~/Images/Screenshots/%d-%m-%Y ; mv $f ~/Images/Screenshots/%d-%m-%Y/'
fi
