#!/bin/sh

if (( $# != 1 )); then
	>&2 echo "Error: Only one argument is required"
	exit 1
fi

if [[ ! -f "$1" ]]; then
    >&2 echo "Error: file $1 doesn't exist"
    exit 1
fi

name=${1%.*}
jupyter nbconvert --to latex "$name.ipynb"
sed -i '1 a \\\usepackage[english,russian]{babel}' "$name.tex"
sed -i '1 a \\\usepackage[utf8]{inputenc}' "$name.tex"
sed -i '1 a \\\author{Dima Glushkov}' "$name.tex"
pdflatex "$name.tex"
pdflatex "$name.tex"
rm "$name.log" "$name.aux" "$name.out"