#!/bin/sh
xorg_conf="/etc/X11/xorg.conf"
xorg_nvidia_conf="/etc/X11/xorg.conf.nvidia"
xorg_intel_conf="/etc/X11/xorg.conf.intel"
mode="None"

# If intel file exists, then nvidia conf is set as default xorg conf
# this means that currently xorg running on dGPU
if [ -f "$xorg_intel_conf" ]; then
    mode="&#xf108; dGPU";
fi
if [ -f "$xorg_nvidia_conf" ]; then
    mode="&#xf109; iGPU";
fi

case "$BLOCK_BUTTON" in
    1)
        if [[ $mode == "&#xf108; dGPU" ]]; then
            mv $xorg_conf $xorg_nvidia_conf
            mv $xorg_intel_conf $xorg_conf
            notify-send "Discrete GPU disabled"
            mode="&#xf109; iGPU"
        elif [[ $mode == "&#xf109; iGPU" ]]; then
            mv $xorg_conf $xorg_intel_conf
            mv $xorg_nvidia_conf $xorg_conf
            notify-send "Discrete GPU enabled"
            mode="&#xf108; dGPU"
        else
            notify-send -u critical "Warning: Unkown GPU state"
        fi
    ;;
esac

echo $mode
