#!/bin/sh
date_block=$(date '+%d %b %Y, %A %H:%M:%S')

case "$BLOCK_BUTTON" in
    1|2|3)
        cal -3 --color=always | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' |  rofi -dmenu -theme calendar -font "Noto Mono 12" -markup-rows -m -3 -p "$date_block" > /dev/null
    esac
echo "&#xf073; $date_block"
