#!/bin/sh

case "$BLOCK_BUTTON" in
	1|2|3)
		pactl set-sink-mute @DEFAULT_SINK@ toggle
		;;
    4)
		pactl set-sink-volume @DEFAULT_SINK@ +5% && pactl set-sink-mute @DEFAULT_SINK@ 0
		;;
	5)
		pactl set-sink-volume @DEFAULT_SINK@ -5% && pactl set-sink-mute @DEFAULT_SINK@ 0
		;;
esac

muted=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{if ($2 == "yes"){print "MUTE"}}')
if [ -n "$muted" ] 
then
	echo -e "&#xf026; $muted%"
else
	pactl get-sink-volume @DEFAULT_SINK@ | awk '{if($5 ~ /[0-9][0-9]%/){print $5}}' | tr -d "%" | awk '{if ($1 == "MUTE" || $1 == 0) {print "&#xf026;", $1 "%"} else if($1 < 45) {print "&#xf027;", $1 "%"} else {print "&#xf028;", $1 "%"}}'
fi